### ISSUE TITLE
`getContractInfo` returns a different address

### ISSUE THREAD

**Issue by alexcambose1** [ourzora/zora-protocol#423]
Hey, I’m seeing an issue with the [getContractInfo](https://github.com/ourzora/zora-protocol/blob/5173fbff56ffcfc1e221dc17435eb0eef4b7eff8/packages/protocol-sdk/src/create/contract-setup.ts#L20) function from the SDK where the returned address is different than the one that actually the deployed contract has. For example the one in the screenshot is the generated one 0xEe94679F9857d32269ed890470b245b5Aa12a18 but actually it ends up as https://basescan.org/token/0xa289322757a36a0e1b61ee7f83e966e9b3057561 after deployment (or from the `SetupNewContract` event)
![image](https://github.com/ourzora/zora-protocol/assets/149409103/b8f281e7-4529-45b3-bbfb-f8a407edf9e3)

**Comment by oveddan** [comment]
hey thanks for reporting this, can reproduce. looking into a fix.

**Comment by neatonk** [comment]
I have had similar issues. In my case I suspect it is due to the use of `msg.sender` in `_hashContract`. This value may change depending on how the transaction is submitted, e.g. when using a paymaster for sponsored transactions.

https://github.com/ourzora/zora-protocol/blob/5988cd0bc6e860d80cbbf74b60c8aa7f31c1b914/packages/1155-contracts/src/factory/ZoraCreator1155FactoryImpl.sol#L145-L159

**Comment by iainnash** [comment]
I believe we plan to deprecate this function due to this and other updates which make it harder to determine the final address.
